services:
  ddns:
    build:
      context: ./services/ddns
      dockerfile: Dockerfile
    container_name: ddns
    restart: unless-stopped
    env_file:
      - ./services/ddns/.env
    command: ["noip-duc"]
    networks:
      - minecraft-network

  minecraft:
    build:
      context: ./services/minecraft
      dockerfile: Dockerfile
    container_name: minecraft
    restart: unless-stopped
    environment:
      - EULA=true
    volumes:
      - ./services/minecraft/server:/app/server
      - ./services/minecraft/backup:/app/backup
    networks:
      - minecraft-network
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "25565:25565"
    depends_on:
      - minecraft
    networks:
      - minecraft-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  minecraft-network:
    driver: bridge
