- name: Create DDNS directory
  ansible.builtin.file:
    path: /ddns
    state: directory
    mode: '0755'

- name: Copy DDNS .env
  ansible.builtin.copy:
    src: ../services/ddns/.env
    dest: /ddns/.env
    mode: '0644'

- name: Check if repo exists
  ansible.builtin.command: ls -la /repository
  register: repo_exists
  failed_when: false
  changed_when: false

- name: Clone repo if not exists
  ansible.builtin.git:
    repo: https://github.com/tbouasli/raspberry.git
    dest: /repository
    version: master
    force: true
    clone: true
    recursive: true

- name: Stop and remove existing containers
  ansible.builtin.command: docker compose -f /repository/docker-compose.yml down --remove-orphans
  failed_when: false

- name: Force remove any remaining containers
  ansible.builtin.command: docker rm -f ddns minecraft nginx
  failed_when: false

- name: Pull docker images
  ansible.builtin.command: docker compose -f /repository/docker-compose.yml pull

- name: Start services
  ansible.builtin.command: docker compose -f /repository/docker-compose.yml up -d