name: Build and Push Services

on:
  push:
    branches: [ main, master ]
    paths:
      - 'services/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'services/**'
  workflow_dispatch:
    inputs:
      services:
        description: 'Comma-separated list of services to build (ddns,minecraft,nginx) or "all"'
        required: false
        default: 'all'
        type: string

env:
  REGISTRY: docker.io

jobs:
  build-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - name: ddns
            image: thomasbouasli/noip-duc
          - name: minecraft
            image: thomasbouasli/minecraft
          - name: nginx
            image: thomasbouasli/nginx

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ matrix.service.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/${{ matrix.service.name }}
        file: ./services/${{ matrix.service.name }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
